"""Public package surface for AuralisVoiceKit."""

from ._version import __version__
from .audio import (
    NoiseProfile,
    VoiceActivityConfig,
    VoiceActivityDetector,
    VoiceSegment,
    WavMetadata,
    apply_gain_pcm16,
    calibrate_noise_pcm16,
    chunk_audio,
    chunk_to_wav_bytes,
    decode_audio_with_ffmpeg,
    ffmpeg_available,
    ffmpeg_install_hint,
    ffmpeg_search_locations,
    iter_wav_chunks,
    is_silent_pcm16,
    normalize_chunks_pcm16,
    normalize_pcm16,
    peak_pcm16,
    read_audio,
    read_audio_as_chunk,
    read_wav,
    read_wav_as_chunk,
    read_wav_metadata,
    resolve_ffmpeg_executable,
    rms_pcm16,
    segment_voice_pcm16,
    write_wav,
)
from .benchmarks import (
    BenchmarkComparisonEntry,
    BenchmarkComparisonReport,
    BenchmarkReport,
    BenchmarkResult,
    benchmark_comparison_to_csv_rows,
    benchmark_report_to_csv_rows,
    generate_synthetic_audio_chunks,
    run_offline_benchmarks,
    run_whisper_comparison_benchmarks,
    write_benchmark_report,
)
from .config import VoiceKitConfig
from .diagnostics import (
    DOCTOR_BUNDLE_SCHEMA,
    DiagnosticCheck,
    DiagnosticStatus,
    DoctorReport,
    create_doctor_bundle,
    run_doctor,
    sanitize_doctor_report,
    write_doctor_bundle,
)
from .events import EventBus, VoiceEvent, VoiceEventType
from .exceptions import (
    AuralisError,
    AudioDeviceNotFound,
    AudioSourceError,
    BackendNotAvailable,
    PermissionRequired,
    TranscriptionError,
)
from .kit import AuralisVoiceKit
from .models import AudioChunk, AudioDevice, AudioEncoding, AudioFormat, TranscriptResult
from .privacy import PrivacyEventLogger, PrivacyLogConfig, event_to_log_record, sanitize_event_payload
from .session import VoiceSession, VoiceSessionConfig, VoiceTurn
from .windows_audio import WindowsAudioErrorHint, windows_audio_error_hint

__all__ = [
    "AuralisError",
    "AuralisVoiceKit",
    "AudioChunk",
    "AudioDevice",
    "AudioDeviceNotFound",
    "AudioSourceError",
    "AudioEncoding",
    "AudioFormat",
    "BackendNotAvailable",
    "BenchmarkComparisonEntry",
    "BenchmarkComparisonReport",
    "BenchmarkReport",
    "BenchmarkResult",
    "DOCTOR_BUNDLE_SCHEMA",
    "DiagnosticCheck",
    "DiagnosticStatus",
    "DoctorReport",
    "EventBus",
    "PermissionRequired",
    "PrivacyEventLogger",
    "PrivacyLogConfig",
    "TranscriptResult",
    "TranscriptionError",
    "VoiceEvent",
    "VoiceEventType",
    "VoiceKitConfig",
    "VoiceSession",
    "VoiceSessionConfig",
    "VoiceTurn",
    "WindowsAudioErrorHint",
    "NoiseProfile",
    "VoiceActivityConfig",
    "VoiceActivityDetector",
    "VoiceSegment",
    "WavMetadata",
    "__version__",
    "apply_gain_pcm16",
    "calibrate_noise_pcm16",
    "chunk_audio",
    "chunk_to_wav_bytes",
    "create_doctor_bundle",
    "decode_audio_with_ffmpeg",
    "event_to_log_record",
    "ffmpeg_available",
    "ffmpeg_install_hint",
    "ffmpeg_search_locations",
    "benchmark_comparison_to_csv_rows",
    "benchmark_report_to_csv_rows",
    "generate_synthetic_audio_chunks",
    "iter_wav_chunks",
    "is_silent_pcm16",
    "normalize_chunks_pcm16",
    "normalize_pcm16",
    "peak_pcm16",
    "read_audio",
    "read_audio_as_chunk",
    "read_wav",
    "read_wav_as_chunk",
    "read_wav_metadata",
    "resolve_ffmpeg_executable",
    "rms_pcm16",
    "run_doctor",
    "run_offline_benchmarks",
    "run_whisper_comparison_benchmarks",
    "sanitize_doctor_report",
    "sanitize_event_payload",
    "segment_voice_pcm16",
    "write_wav",
    "write_benchmark_report",
    "write_doctor_bundle",
    "windows_audio_error_hint",
]
