from pathlib import Path
import unittest

import auralis_voicekit


ROOT = Path(__file__).resolve().parents[1]
API_DOC = ROOT / "docs" / "auralisvoicekit-api.html"
MAIN_DOC = ROOT / "docs" / "auralisvoicekit-documentacion.html"
README = ROOT / "README.md"
PRIVACY = ROOT / "PRIVACY.md"
CUSTOM_OUTPUT = ROOT / "CUSTOM_OUTPUT_BACKENDS.md"
SYSTEM_OUTPUT_DEMO = ROOT / "examples" / "system_output_demo.py"
LOCAL_ASSISTANT_PRIVACY_DEMO = ROOT / "examples" / "local_assistant_privacy_demo.py"
PILOTS = ROOT / "PILOTS.md"
PILOT_FINDINGS = ROOT / "PILOT_FINDINGS.md"
BETA_CHECKLIST = ROOT / "BETA_CHECKLIST.md"
BETA_EVIDENCE_REQUIREMENTS = ROOT / "BETA_EVIDENCE_REQUIREMENTS.md"
PILOT_RUN = ROOT / "tools" / "pilot_run.py"
MANUAL_PILOT = ROOT / "tools" / "manual_pilot.py"
OUTPUT_PILOT = ROOT / "tools" / "output_pilot.py"
TRANSCRIPTION_PILOT = ROOT / "tools" / "transcription_pilot.py"
BETA_READINESS = ROOT / "tools" / "beta_readiness.py"


class DocumentationTests(unittest.TestCase):
    def test_api_reference_documents_public_exports(self):
        content = API_DOC.read_text(encoding="utf-8")

        missing = [name for name in auralis_voicekit.__all__ if name not in content]

        self.assertEqual(missing, [])

    def test_public_docs_link_api_reference(self):
        api_name = "auralisvoicekit-api.html"

        self.assertIn(api_name, MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn(api_name, README.read_text(encoding="utf-8"))

    def test_api_reference_has_pypi_install_and_custom_backend_sections(self):
        content = API_DOC.read_text(encoding="utf-8")

        self.assertIn("python -m pip install auralisvoicekit", content)
        self.assertIn("Backends personalizados", content)
        self.assertIn("ffmpeg_search_locations", content)
        self.assertIn("run_offline_benchmarks", content)

    def test_output_queue_is_documented(self):
        readme = README.read_text(encoding="utf-8")
        main_doc = MAIN_DOC.read_text(encoding="utf-8")
        api_doc = API_DOC.read_text(encoding="utf-8")

        for content in (readme, main_doc, api_doc):
            self.assertIn("queue_speech", content)
            self.assertIn("queue_speech_many", content)
            self.assertIn("drain_output_queue", content)
            self.assertIn("clear_output_queue", content)
            self.assertIn("output_queue_size", content)

    def test_session_activation_is_documented(self):
        readme = README.read_text(encoding="utf-8")
        main_doc = MAIN_DOC.read_text(encoding="utf-8")
        api_doc = API_DOC.read_text(encoding="utf-8")

        for content in (readme, main_doc, api_doc):
            self.assertIn("activation_phrases", content)
            self.assertIn("require_activation", content)
            self.assertIn("activation_hook", content)
        self.assertIn("turn_is_activated", api_doc)

    def test_transcription_timeout_is_documented(self):
        readme = README.read_text(encoding="utf-8")
        main_doc = MAIN_DOC.read_text(encoding="utf-8")
        api_doc = API_DOC.read_text(encoding="utf-8")

        for content in (readme, main_doc, api_doc):
            self.assertIn("transcription_timeout_seconds", content)
            self.assertIn("AURALIS_TRANSCRIPTION_TIMEOUT_SECONDS", content)
            self.assertIn("--timeout-seconds", content)
            self.assertIn("--preflight-backend", content)
            self.assertIn("--preflight-timeout-seconds", content)
            self.assertIn("--require-openai-api-key", content)
            self.assertIn("credentials.openai_api_key_present", content)
            self.assertIn("credentials.records_openai_api_key", content)

    def test_pyaudio_optional_backend_is_documented(self):
        readme = README.read_text(encoding="utf-8")
        main_doc = MAIN_DOC.read_text(encoding="utf-8")
        api_doc = API_DOC.read_text(encoding="utf-8")

        self.assertIn("auralisvoicekit[pyaudio]", readme)
        self.assertIn("--backend pyaudio", readme)
        self.assertIn("pyaudio_capture.py", main_doc)
        self.assertIn("--backend pyaudio", main_doc)
        self.assertIn("PyAudioCaptureBackend", api_doc)
        self.assertIn("auralisvoicekit[pyaudio]", api_doc)

    def test_privacy_guide_is_linked_from_public_docs(self):
        privacy_name = "PRIVACY.md"

        self.assertTrue(PRIVACY.exists())
        self.assertIn(privacy_name, README.read_text(encoding="utf-8"))
        self.assertIn(privacy_name, MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("PrivacyEventLogger", API_DOC.read_text(encoding="utf-8"))

    def test_custom_output_guide_and_stability_gate_are_linked(self):
        custom_output_name = "CUSTOM_OUTPUT_BACKENDS.md"

        self.assertTrue(CUSTOM_OUTPUT.exists())
        self.assertIn(custom_output_name, README.read_text(encoding="utf-8"))
        self.assertIn(custom_output_name, MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn(custom_output_name, API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/stability_gate.py", README.read_text(encoding="utf-8"))

    def test_system_output_demo_is_linked_from_public_docs(self):
        system_output_name = "system_output_demo.py"

        self.assertTrue(SYSTEM_OUTPUT_DEMO.exists())
        self.assertIn(system_output_name, README.read_text(encoding="utf-8"))
        self.assertIn(system_output_name, MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn(system_output_name, API_DOC.read_text(encoding="utf-8"))

    def test_local_assistant_privacy_demo_is_linked_from_public_docs(self):
        demo_name = "local_assistant_privacy_demo.py"

        self.assertTrue(LOCAL_ASSISTANT_PRIVACY_DEMO.exists())
        self.assertIn(demo_name, README.read_text(encoding="utf-8"))
        self.assertIn(demo_name, MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn(demo_name, API_DOC.read_text(encoding="utf-8"))

    def test_pilot_runbook_and_runner_are_linked_from_public_docs(self):
        self.assertTrue(PILOTS.exists())
        self.assertTrue(PILOT_FINDINGS.exists())
        self.assertTrue(BETA_CHECKLIST.exists())
        self.assertTrue(BETA_EVIDENCE_REQUIREMENTS.exists())
        self.assertTrue(PILOT_RUN.exists())
        self.assertTrue(MANUAL_PILOT.exists())
        self.assertTrue(OUTPUT_PILOT.exists())
        self.assertTrue(TRANSCRIPTION_PILOT.exists())
        self.assertTrue(BETA_READINESS.exists())
        self.assertIn("PILOTS.md", README.read_text(encoding="utf-8"))
        self.assertIn("PILOT_FINDINGS.md", README.read_text(encoding="utf-8"))
        self.assertIn("BETA_CHECKLIST.md", README.read_text(encoding="utf-8"))
        self.assertIn("BETA_EVIDENCE_REQUIREMENTS.md", README.read_text(encoding="utf-8"))
        self.assertIn("PILOTS.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("PILOT_FINDINGS.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("BETA_CHECKLIST.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("BETA_EVIDENCE_REQUIREMENTS.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("PILOTS.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("BETA_CHECKLIST.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("BETA_EVIDENCE_REQUIREMENTS.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools\\pilot_run.py", README.read_text(encoding="utf-8"))
        self.assertIn("tools\\manual_pilot.py", README.read_text(encoding="utf-8"))
        self.assertIn("tools\\output_pilot.py", README.read_text(encoding="utf-8"))
        self.assertIn("tools\\pilot_audio_fixture.py", README.read_text(encoding="utf-8"))
        self.assertIn("tools\\transcription_pilot.py", README.read_text(encoding="utf-8"))
        self.assertIn("tools\\beta_readiness.py", README.read_text(encoding="utf-8"))
        self.assertIn("--evidence", README.read_text(encoding="utf-8"))
        self.assertIn("pilot-plan.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-findings-template.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-handoff.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-command-pack.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-environment-checklist.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-fixture-preflight.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-transcription-readiness.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-system-output-readiness.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-evidence-manifest.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-decision-gate.md", README.read_text(encoding="utf-8"))
        self.assertIn("evidence_manifest", README.read_text(encoding="utf-8"))
        self.assertIn("fixture_preflight_card", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_readiness_card", README.read_text(encoding="utf-8"))
        self.assertIn("system_output_readiness_card", README.read_text(encoding="utf-8"))
        self.assertIn("pilot_decision_gate", README.read_text(encoding="utf-8"))
        self.assertIn("recommended_pilot_sequence", README.read_text(encoding="utf-8"))
        self.assertIn("platform_pilot_matrix", README.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_required", README.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_flag", README.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_field", README.read_text(encoding="utf-8"))
        self.assertIn("--run-preflight", README.read_text(encoding="utf-8"))
        self.assertIn("--preflight-only", README.read_text(encoding="utf-8"))
        self.assertIn("--max-audio-seconds", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-audio-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-reference-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-quality-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn("transcription-review-checklist.md", README.read_text(encoding="utf-8"))
        self.assertIn("real-transcription-next-step.md", README.read_text(encoding="utf-8"))
        self.assertIn("target_backend_ready_required", README.read_text(encoding="utf-8"))
        self.assertIn("target_backend.install_plan", README.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision", README.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision.decision", README.read_text(encoding="utf-8"))
        self.assertIn("auralisvoicekit[whisper]", README.read_text(encoding="utf-8"))
        self.assertIn("audio.generated_synthetic_audio", README.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_confirmed_non_sensitive", README.read_text(encoding="utf-8"))
        self.assertIn("audio.decoded", README.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_file_name_redacted", README.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.enabled", README.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.passed", README.read_text(encoding="utf-8"))
        self.assertIn("transcript.text_redacted", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_audio_file_name", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_expected_text_file_name", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_transcript_text", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_expected_text", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.audio_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("reference_privacy_scan.passed", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_privacy_scan_passed", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.quality_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.ready_for_beta_evidence", README.read_text(encoding="utf-8"))
        self.assertIn("output-operator-checklist.md", README.read_text(encoding="utf-8"))
        self.assertIn("system-output-next-step.md", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-text-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn("text_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("spoken_text_privacy_scan.passed", README.read_text(encoding="utf-8"))
        self.assertIn("output_backend_ready_required", README.read_text(encoding="utf-8"))
        self.assertIn("target_output_backend.readiness_plan", README.read_text(encoding="utf-8"))
        self.assertIn("speech-dispatcher", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.records_operator_identity", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.redacts_spoken_text", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.commands_available", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_real_audio", README.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.uses_placeholders", README.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_spoken_text", README.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_operator_identity", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.text_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.spoken_text_privacy_scan_passed", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-voice-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn('"Windows|Linux|Darwin"', README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.expected_system_matched", README.read_text(encoding="utf-8"))
        self.assertIn("--confirm-input-reviewed", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.voice_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_beta_evidence", README.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-checklist.md", README.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-command.md", README.read_text(encoding="utf-8"))
        self.assertIn("manual_capture_command_card", README.read_text(encoding="utf-8"))
        self.assertIn("input_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("capture_readiness_plan", README.read_text(encoding="utf-8"))
        self.assertIn("--target-system", README.read_text(encoding="utf-8"))
        self.assertIn("--require-capture-backend-ready", README.read_text(encoding="utf-8"))
        self.assertIn("target_capture_backend", README.read_text(encoding="utf-8"))
        self.assertIn("capture_backend_ready_required", README.read_text(encoding="utf-8"))
        self.assertIn("libportaudio2", README.read_text(encoding="utf-8"))
        self.assertIn("brew install portaudio", README.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.input_review_confirmed", README.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.ready_for_beta_evidence", README.read_text(encoding="utf-8"))
        self.assertIn("--expected-system", README.read_text(encoding="utf-8"))
        self.assertIn("system_guard.expected_system_matched", README.read_text(encoding="utf-8"))
        self.assertIn("tools/pilot_run.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/manual_pilot.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/output_pilot.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/pilot_audio_fixture.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/transcription_pilot.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/beta_readiness.py", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--evidence", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("pilot-plan.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-findings-template.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-handoff.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-command-pack.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-environment-checklist.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-fixture-preflight.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-transcription-readiness.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-system-output-readiness.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-evidence-manifest.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-decision-gate.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("evidence_manifest", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("fixture_preflight_card", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_readiness_card", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("system_output_readiness_card", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("pilot_decision_gate", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("recommended_pilot_sequence", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("platform_pilot_matrix", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_required", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_flag", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_field", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--run-preflight", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--preflight-only", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--max-audio-seconds", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-audio-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-reference-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-quality-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription-review-checklist.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-transcription-next-step.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_backend_ready_required", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_backend.install_plan", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision.decision", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("auralisvoicekit[whisper]", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.generated_synthetic_audio", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_confirmed_non_sensitive", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.decoded", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_file_name_redacted", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.enabled", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.passed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcript.text_redacted", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_audio_file_name", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_expected_text_file_name", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_transcript_text", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_expected_text", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.audio_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("reference_privacy_scan.passed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_privacy_scan_passed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.quality_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.ready_for_beta_evidence", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("output-operator-checklist.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("system-output-next-step.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-text-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("text_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("spoken_text_privacy_scan.passed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("output_backend_ready_required", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_output_backend.readiness_plan", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("speech-dispatcher", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.records_operator_identity", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.redacts_spoken_text", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.commands_available", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_real_audio", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.uses_placeholders", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_spoken_text", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_operator_identity", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.text_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.spoken_text_privacy_scan_passed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-voice-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn('"Windows|Linux|Darwin"', MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.expected_system_matched", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-input-reviewed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.voice_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_beta_evidence", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-checklist.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-command.md", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual_capture_command_card", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("input_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_readiness_plan", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--target-system", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--require-capture-backend-ready", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_capture_backend", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_backend_ready_required", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("libportaudio2", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("brew install portaudio", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.input_review_confirmed", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.ready_for_beta_evidence", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("--expected-system", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("system_guard.expected_system_matched", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/pilot_run.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/manual_pilot.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/output_pilot.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/pilot_audio_fixture.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/transcription_pilot.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("tools/beta_readiness.py", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--evidence", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("pilot-plan.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-findings-template.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-handoff.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-command-pack.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-environment-checklist.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-fixture-preflight.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-transcription-readiness.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-system-output-readiness.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-evidence-manifest.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-pilot-decision-gate.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("evidence_manifest", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("fixture_preflight_card", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_readiness_card", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("system_output_readiness_card", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("pilot_decision_gate", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("recommended_pilot_sequence", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("platform_pilot_matrix", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_required", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_flag", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("strict_backend_guard_field", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--run-preflight", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--preflight-only", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--max-audio-seconds", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-audio-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-reference-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-quality-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription-review-checklist.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("real-transcription-next-step.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_backend_ready_required", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_backend.install_plan", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("preflight_decision.decision", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("auralisvoicekit[whisper]", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.generated_synthetic_audio", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_confirmed_non_sensitive", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.decoded", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.audio_file_name_redacted", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.enabled", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("audio.duration_gate.passed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcript.text_redacted", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_audio_file_name", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.records_expected_text_file_name", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_transcript_text", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.redacts_expected_text", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.audio_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("reference_privacy_scan.passed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.reference_privacy_scan_passed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.quality_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("transcription_checklist.ready_for_beta_evidence", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("output-operator-checklist.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("system-output-next-step.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-text-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("text_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("spoken_text_privacy_scan.passed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("output_backend_ready_required", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_output_backend.readiness_plan", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("speech-dispatcher", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.records_operator_identity", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.redacts_spoken_text", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.commands_available", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_real_audio", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.uses_placeholders", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_spoken_text", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("next_system_output.records_operator_identity", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.text_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.spoken_text_privacy_scan_passed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-voice-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn('"Windows|Linux|Darwin"', API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.expected_system_matched", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--confirm-input-reviewed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.voice_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("operator_checklist.ready_for_beta_evidence", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-checklist.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual-capture-command.md", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("manual_capture_command_card", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("input_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_readiness_plan", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--target-system", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--require-capture-backend-ready", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("target_capture_backend", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_backend_ready_required", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("libportaudio2", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("brew install portaudio", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.input_review_confirmed", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("capture_checklist.ready_for_beta_evidence", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("--expected-system", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("system_guard.expected_system_matched", API_DOC.read_text(encoding="utf-8"))

    def test_doctor_bundle_is_documented(self):
        self.assertIn("--bundle", README.read_text(encoding="utf-8"))
        self.assertIn("--bundle", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("write_doctor_bundle", API_DOC.read_text(encoding="utf-8"))
        self.assertIn("doctor-bundles", README.read_text(encoding="utf-8"))
        self.assertIn("doctor-bundles", MAIN_DOC.read_text(encoding="utf-8"))
        self.assertIn("analyze_doctor_bundles", API_DOC.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
